project:
  type: website

website:
  title: "fr.anckalbi.net"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/franckalbinet
format:
  html:
    theme: 
      - litera
      - custom.scss
    css: styles.css
    

